# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text=b'Day of booking', verbose_name='Day of booking')),
                ('start_time', models.TimeField(help_text=b'Booking slot', verbose_name='Booking slot')),
                ('end_time', models.TimeField(help_text=b'Finish Time', verbose_name='Finish time')),
                ('notes', models.TextField(blank=True, help_text=b'Notes', null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
