# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 23:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Booking date')),
                ('start_time', models.TimeField(choices=[(datetime.time(11, 0), '11 AM'), (datetime.time(12, 0), '12 PM'), (datetime.time(13, 0), '1 PM'), (datetime.time(14, 0), '2 PM'), (datetime.time(15, 0), '3 PM'), (datetime.time(16, 0), '4 PM'), (datetime.time(17, 0), '5 PM')], max_length=200, verbose_name='Booking time')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Notes')),
                ('stripe_id', models.CharField(default=b'', max_length=40)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to=b'images')),
                ('description', models.TextField()),
                ('slots', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='type_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Product'),
        ),
    ]
