# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20181004_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(choices=[(1, b'9:00 am'), (2, b'10:00 am'), (3, b'11:00 am'), (4, b'12:00 am'), (5, b'1:00 pm')], help_text=b'Finish Time', max_length=200, verbose_name='Finish time'),
        ),
    ]
