# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20181004_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(choices=[(1, 900), (2, 1000), (3, 1100), (4, 1200), (5, 1300)], help_text=b'Finish Time', max_length=200, verbose_name='Finish time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.CharField(choices=[(1, 900), (2, 1000), (3, 1100), (4, 1200), (5, 1300)], help_text=b'Booking slot', max_length=200, verbose_name='Booking slot'),
        ),
    ]
