# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20181004_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slots', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='session_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_type', to='bookings.Session'),
            preserve_default=False,
        ),
    ]
