# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_auto_20181013_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.CharField(blank=True, help_text=b'Notes', max_length=500, null=True, verbose_name='Notes'),
        ),
    ]
