# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_auto_20181013_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_id',
            field=models.CharField(default=b'', max_length=40),
        ),
    ]
