# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_booking_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.FloatField(default=2.99),
            preserve_default=False,
        ),
    ]
